### ISSUE TITLE
My Art Page

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#1]
## Value proposition

As an artist
I want to show pictures of all my art
So that people can see all my projects

## Description

![Bildschirmfoto 2023-08-13 um 13 54 50](https://github.com/DorisW3/capstone-project/assets/135646413/f063bb11-b052-4d54-965e-24bb98159388)

## Acceptance criteria

- [x] A selection of artworks with a description is shown in a list 
- [x] one should be able to scroll the page vertical
- [x] all pictures can have different sizes, but also have to fit in the display area

## Tasks

- [x] create a branch my-art
- [x] lib-folder with db.json: an array of objects with data
- [x] component Picture
- [x] component PictureList
- [x] map over array to display all pictures to fetch all objects 
- [x] scroll feature 

## Size

'M'
