### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#13]
## Value proposition

As an artist
 I want to  be able to upload pictures of my new artwork
 In order to present them to other users

## Description

![Bildschirmfoto 2023-08-24 um 12 01 30](https://github.com/DorisW3/capstone-project/assets/135646413/0aa6fc6c-d9dc-482f-baba-bbba81fe3891)

## Acceptance criteria

- [x] it should be displayed a feature to upload an image  
- [x] one should be able to click the feature so that there is a pop-up window, in which  the user can chose an 
       image to be uploaded 
- [x] there should be a “share” button which saves the image on the top of the already displayed images

## Tasks

- [x] create new branch feat/image-up-load 
- [x] follow the instructions on:
         https://github.com/actyvystom/cloudinary-demo/blob/update-next/README.md

## Size

'M'

**Comment by izabelladobielewska** [comment]
looks good:)
