### ISSUE TITLE
fake login

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#16]
## Value proposition

As an user 
I want to  be able to log in into the app   
In order to protect my private data and profile page (= “My Art” page) with the  overview about my “uploaded” pictures

## Description

![Bildschirmfoto 2023-08-30 um 11 30 42](https://github.com/DorisW3/capstone-project/assets/135646413/b9a0ae32-2a98-46a4-98e8-ea4b244cb9e9)

## Acceptance criteria

- [x] there should be a login page with input fields for “username” and “password” which simulate a login module
- [x] the input fields should be useable to fill in username respectively password 
- [x]  a button confirming the login
- [x] logout feature in the header of all pages
- [ ] #19

## Tasks

- [x] create branch feat/fake-login
- [x] create a form with two input fields for “username” and “password”
- [x] add button to execute the login  
- [x] add a text field that confirms “login successful ” 
- [x] add a logout button which can be seen on all pages

## Size

'M'

**Comment by F-Kirchhoff** [comment]
Very nice user story!
