### ISSUE TITLE
App styling

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#17]
## Value proposition

As an user  
I want to have a nicer user experience in an appealing app  
In order to use the app more often

## Description

- adding a logo in the heading 
- changing the navigation buttons into cute icons
- a few other styling adjustments

## Acceptance criteria

- [x] everything works as before
- [x] the app looks more appealing

## Tasks

- [x] create new branch feat/styling
- [x] add app logo on all pages in the heading
- [x] replace the navbar buttons with some icons
- [x] adjust some other styling 

## Size

'M - L'
