### ISSUE TITLE
details & comment page

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#2]
## Value proposition

As an artist
I want to see the details of a picture and be able to comment pictures or ask questions about it
So that I can discuss about the artwork with other users

## Description

![Bildschirmfoto 2023-08-15 um 16 11 40](https://github.com/DorisW3/capstone-project/assets/135646413/4480f4b8-6f59-400b-91dc-682ec3b0773a)

## Acceptance criteria

- [x] a details page which shows the picture of a single artwork, including all details about it 
- [x] the possibility to add a new comment
- [x] a list of all comments (including date, title & comment) above and the latest on top
- [x] a button to send the comment
- [x] clicking on the "send" button shows the created comment as newest entry at the top of the comment list and
        turns the form blank, so that it can be refilled

## Tasks

- [x] create a branch details-page
- [x] component SinglePicture or SingleImage (have to think about the syntax during the coding)
- [x] component EntryForm: form with two input fields (title & comment), the current date and a submit button
- [x] create submit button designated as "create" button
- [x] component CommentList which renders all entries, with most recent entry on top 

## Size

'M'

**Comment by KevinKyaterekera** [comment]
hey doris, maybe you could add more details to the acceptance criteria, because the button isnt mentioned but required in your tasks. what happens with the form, after its send? does it just turns blank? 

maybe like "clicking on the button turns the form blank, so that i can refill it"

otherwise I find it good :)

**Comment by ninaassmann** [comment]
looks good to me, just a typo
=> a comment page **which** (witch = Hexe ;) ) shows the picture of one artwork
