### ISSUE TITLE
delete image

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#21]
## Value proposition

As an user
I want to  have a delete button 
In order to remove images I don't wanna share anymore

## Description

![Bildschirmfoto 2023-09-08 um 15 59 35](https://github.com/DorisW3/capstone-project/assets/135646413/ed77785e-9673-4c3b-a2f7-ecec6aec6027)

## Acceptance criteria

- [ ] there should be a delete button under every image
- [ ] the button should be clickable
- [ ] pop up of alert message "do you really want to delete this image?" with "Yes" or  "no" 
        buttons

## Tasks

- [ ] create branch feat/delete-image
- [ ] create component delete button
- [ ] build delete functionality

**Comment by chris-kuehn** [comment]
LGTM! :)
