### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#3]
## Value proposition

As a user
I want to switch between the existing pages
In order to be able to see every page

## Description

![Bildschirmfoto 2023-08-15 um 15 38 20](https://github.com/DorisW3/capstone-project/assets/135646413/362b4249-e081-4378-8260-9b381ea6e998)

## Acceptance criteria

- [x] one can choose to look at the "Overview" Page or "My Art" page
- [x] clicking a navigation link should guide to "MyArt" page or "Overview" Page
- [x] if there is an error, show “404 Page not found”

## Tasks

- [x] create branch feat/navbar
- [x] move the function "MyArt" from index.js to a new file "myart.js", so there are two pages (Overview & myArt)
- [x] create component NavBar in a new component file Navbar.js
- [x] with a function NavBar returning two links (MyArt & CommentPage) which are styled like buttons

## Size

'S'

**Comment by Roland-Hufnagel** [comment]
Hi Doris, this US is not very clear to me. When you use your navigation to switch to the comment-page, what will it display? I think the 'MyArt' Link will link to the homepage (a list of arts) and I don't know what the 'commentPage' is. Maybe you can give an example in the wireframe. 
Or do you mean an Art's Detailpage? Like when you click on one art in the list, a detailpage shows this art with the possibility to leave a comment? If you want this feature, you should not use a navigation but render each art in the list as a Link, which leads to the corresponding detailpage.

Please make things a bit clearer. And each task should stand alone (don't write one sentence over three tasks)

**Comment by ninaassmann** [comment]
better use the Link component from nextJS to switch the sites
You don't need a eventListener here. It works like an a tag and you can switch easily between the pages

<Link href="/myart">My Art</Link>

https://nextjs.org/docs/pages/api-reference/components/link

**Comment by DorisW3** [comment]
true! I forgot about that...

**Comment by ninaassmann** [comment]
LGTM
