### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#5]
## Value proposition

As an user
I want to see all the pictures users or myself posted at the overview
In order to have all images of different users in one look

## Description

![Bildschirmfoto 2023-08-15 um 15 57 59](https://github.com/DorisW3/capstone-project/assets/135646413/2d59d5f0-dde0-4e36-9c1a-128651c916d0)

## Acceptance criteria

- [x] present an overview page with pictures of different users or oneself posted
- [x]  all pictures of users are displayed with the associated username 
- [x] below there also are all pictures of MyArt-page, which are currently displayed on the same page
- [x] if there is an error, show “404 Page not found”

## Tasks

- [x]  create a new branch feat/homepage 
- [x] in the index.js call a function Homepage (there are two functions then: myArt & Homepage which currently displayed 
        on the same page)
- [x] use map-method to render all pictures with usernames
- [x] all pictures have different sizes, but fit in the container

## Size

'S'

**Comment by jonas8900** [comment]
the Value proposition is a bit confusing, could you maybe change it to a shorter description? 
like this: 

As a user,
I want to see all pictures the users posted,
to have all of them on one page

**Comment by mbosselmann** [comment]
Hi Doris,
good job! 💪 I like Jonas' suggestion! And I also think it could be nice to know that this page also shows the pictures of the user (my art) (below or above the other pictures?) and should be mentioned in the acceptance criteria. :)

**Comment by jonas8900** [comment]
sorry i deleted my post! heres the old one: 

your Value proposition is a bit confusing, could you make this a little bit shorter ? 

like this: 
As a user
i want to see all the pictures, the users posted
to have all of them displayed on one page

**Comment by mbosselmann** [comment]
LGTM!
