### ISSUE TITLE
Favorite and follow button

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#7]
## Value proposition

As an user
 I want to follow artists whom I like and be able to set images to the “favorite” state by clicking the favorite button 
In order to have an interactive user experience

## Description

<img width="540" alt="Bildschirmfoto 2023-08-16 um 04 39 48" src="https://github.com/DorisW3/capstone-project/assets/135646413/9a67b51f-930f-44ac-8a03-d80fab5e2891">

## Acceptance criteria

- [x] insert a “favorite” button to all pictures on both displayed pages
- [x] add a “follow” button beside the username under all pictures of the 
        “Overview” page  
 - [x] both buttons should be marked with a different color when they are 
         clicked for change to “favorite” or “follow”
- [x] both buttons should be unmarked (initial version of button) for change 
        to undo “favorite” or “follow”

## Tasks

- [x] create branch feat/fav-follow-button
- [x] write a component Button with function Button containing 
        handleEventListener(onClick){} for both buttons  with a 
        classList.toggle() method between marked and unmarked
- [x] add button icons in public folder and use them in the toggle method  

## Size

"S"

**Comment by milodevhh** [comment]
Hey Doris, sound wonderful. That is really nice that you also want to give the option the username(artist) to follow, Why do want do that all in one us may be you split it or?

**Comment by DorisW3** [comment]
Dear Milo,
thank you for reviewing my US. Unfortunately, I have to say that it was a little hard to read and understand.
I didn't spilt the US, because the basic functionality of both buttons is the same.

**Comment by dm-nosov** [comment]
✔️ insert a “favorite” button to all pictures on both displayed pages
✔️add a “follow” button beside the username under all pictures of the
“Overview” page  
✔️ both buttons should be marked with a different color when they are
clicked for change to “favorite” or “follow”
✔️ both buttons should be unmarked (initial version of button) for change
to undo “favorite” or “follow”
