### ISSUE TITLE
Favorites page

### ISSUE THREAD

**Issue by DorisW3** [DorisW3/capstone-project#9]
## Value proposition

As an user
 I want to have an overview about all artworks I added as my “favorites”
 In order to see them on one page

## Description

![Bildschirmfoto 2023-08-17 um 17 22 31](https://github.com/DorisW3/capstone-project/assets/135646413/3e5fa59e-abdd-4b2c-a99e-febdf074c2de)

## Acceptance criteria

- [x] display a new page “Favorites”
- [x] add a favorites link to the navigation to be able to switch to the favorites page
- [x] show all pictures which were marked as favorites  
- [x] below every image represent the according username
- [x] clicking the favorite button to mark and unmark should be possible 

## Tasks

- [x] create branch feat/favorites
- [x] create favorites.js & function Favorites
- [x] add link “Favorites”, styled like a button, to navbar 
- [x] use filter&map-method to render the pictures & usernames
- [x] display only pictures which are “favorite” via ternary operator: FavoriteButton ? marked : none
